# Generated by Django 5.2.6 on 2025-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='franchise',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
